// client
export const SIGNUP_REQUESTING = 'SIGNUP_REQUESTING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNIN_REQUESTING = 'SIGNIN_REQUESTING';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const CLIENT_ERROR = 'CLIENT_ERROR';
export const USER_ADD_AVATAR = 'USER_ADD_AVATAR';
export const USER_UPDATE_PHONENUMBER = 'USER_UPDATE_PHONENUMBER';
// todos
export const TODOS_INDEX_REQUESTING = 'TODOS_INDEX_REQUESTING';
export const TODOS_INDEX_SUCCESS = 'TODOS_INDEX_SUCCESS';
export const TODO_POST_REQUESTING = 'TODO_POST_REQUESTING';
export const TODO_POST_SUCCESS = 'TODO_POST_SUCCESS';
export const TODO_REMINDER_POST_REQUESTING =
  'TODO_REMINDER_POST_REQUESTING';
export const TODO_REMINDER_POST_SUCCESS =
  'TODO_REMINDER_POST_SUCCESS';
export const TODOS_DELETE_REQUESTING = 'TODOS_DELETE_REQUESTING';
export const TODOS_DELETE_SUCCESS = 'TODOS_DELETE_SUCCESS';
export const TODOS_ERROR = 'TODOS_ERROR';
